### ISSUE TITLE
Popups are too persistent (do not hide when appropriate)

### ISSUE THREAD

**Issue by kanitw** [uwdata/lyra#118]
I edit something in the scale and then mistakenly click something on the canvas.
but the scale popup stay here forever until I click close it.  

![lyra-39](https://f.cloud.github.com/assets/111269/2224493/7cdb8a78-9a7f-11e3-82d4-2f078ea9770d.png)

Anyway, I think it’s not that important for now.  

But in general, I think popups are usually problematic.  We might think about other UIs for this in the future.

**Comment by arvind** [comment]
Lyra 2 will, thankfully, only use popovers for hints and tutorials.
