### ISSUE TITLE
Should dragging same data field to both `width` and `height` drop zones in same visualization use same scale?

### ISSUE THREAD

**Issue by kanitw** [uwdata/lyra#141]
**Steps**
1) select `jobs`  as source
2) drag year to `height` drop zone (the user’s correction)
3) drag year to `width` drop zone (the user’s correction)

Two axes will be created using same scale `Y` both of them are named `Y Axis`. 

![lyra-6](https://f.cloud.github.com/assets/111269/2240956/cc25a73c-9cb7-11e3-8ba3-5eb25dd1e02f.png)

I think the `X` one should be named `X Axis` and use another new scale called `X`.

**Comment by arvind** [comment]
We defer dropzone decisions to Vega-Lite now :)
