### ISSUE TITLE
Removing a schema from expr container doesn’t remove that value from `item.exprFields`

### ISSUE THREAD

**Issue by kanitw** [uwdata/lyra#144]
**Steps**
1) select `olympics` as source
2) add text marks
3) drag `ISO_country_code` to text property on the right pane.
4) remove `ISO_country_code` from the text property
5) Add breakpoint in `inspectors.js` around line 320 (inside the following line

```
      $(element).find('.expr')
        // .html(scope.$parent.ngModel)
        .drop(function(e, dd) {
           … // anywhere in this function!
```
6) drag `Country_name` to text property
7) in the breakpoint, get value `scope.item.exprField` — we can see that it still contains `ISO_country_code` even though it’s removed.

**Comment by arvind** [comment]
Need to re-think how we do expression parsing with Lyra 2. Hopefully something more robust than our older approach.
