### ISSUE TITLE
Alert when user wants to delete a pipeline

### ISSUE THREAD

**Issue by ZeningQu** [uwdata/lyra#159]
Deleting a pipeline breaks the links between the specification and the visualization in the canvas (judging from the errors that appear in the console). When a user clicks on the "-" button, it would be great if lyra could alert the user that deleting the pipeline will affect the visualization, and ask the user if he/she really wants to delete or not.

For example, this is napoleon visualization demo:
![screen shot 2014-02-26 at 1 53 41 pm](https://f.cloud.github.com/assets/822034/2276307/b7eb0a4c-9f31-11e3-9071-98ac724982ad.png)

After I deleted all pipelines, the visualization in the canvas doesn't change (see image below), but there are some errors in the console. 
![screen shot 2014-02-26 at 1 54 02 pm](https://f.cloud.github.com/assets/822034/2276329/0d401708-9f32-11e3-84c5-445bef0de8a7.png)

It would be great if lyra could warn me that deleting a pipeline will cause changes in the canvas.

**Comment by arvind** [comment]
Pipelines cannot be deleted in Lyra 2. Perhaps they should be deletable but only if no other primitives rely on them.
