### ISSUE TITLE
Loading External JSON Data Source via URL just hangs

### ISSUE THREAD

**Issue by wattsteve** [uwdata/lyra#180]
I took data/medals.json and created an identical replica called test.json and hosted it off the root webserver directory so that it is accessible at http://localhost/test.json (which I verified). I then went into Lyra and selected "From Source | New Data Source" and gave it a Name, Selected URL and provided the "http://localhost/test.json"  as the URL and selected JSON as the format. I then clicked the "Load" button and it hangs.

**Comment by arvind** [comment]
Closing old issues as we begin work on Lyra 2. Issues related to data import will now be tracked in #235.
