### ISSUE TITLE
Add http://uwdata.github.io/lyra/ Demo page.

### ISSUE THREAD

**Issue by sarathsaleem** [uwdata/lyra#215]
If you can create a branch name 'gh-pages' we can publish the application as a public project page (https://help.github.com/articles/user-organization-and-project-pages/#project-pages).

I have forked and created the demo like this. http://sarathsaleem.github.io/lyra/, So if you have a "gh-pages" branch i can give a pull request

**Comment by arvind** [comment]
Thanks for bringing this up. The reason I haven't published Lyra to github pages yet is because Cross-Site security constraints within browsers would make it impossible to load custom/external datasets via a URL. We circumvent this with [our deployed version](http://idl.cs.washington.edu/projects/lyra/app/) by using the proxy.php script to route requests. 

Any ideas on what we can do for gh-pages?

**Comment by domoritz** [comment]
You could serve the gh-pages from a cs domain. We did that for myria.cs.washington.edu. @dhalperi knows how to do this.

**Comment by arvind** [comment]
@domoritz How do you mean serve gh-pages from a cs domain? If all we're doing is pointing a cs address to github, doesn't the issue still persist since I don't believe gh-pages allows any server-side scripting to allow us to route external requests?

**Comment by domoritz** [comment]
Oh, I misunderstood the problem. I thought the problem are resources on a cd domain.

Could you only host the proxy script on our servers and serve Lyra from github?

**Comment by sarathsaleem** [comment]
@arvind  Ok. I was unaware of the deployed [live version]( http://idl.cs.washington.edu/projects/lyra/app/). My intention behind raising this issue this was to give  quick live version to users. So its already taken care.

I think its better to add a link to live version in the master readme page. Since I came directly to the gitpage I was unaware of deployed live version.

Yes you are right, cross site issues cannot be solved straight forward , but has some workaround like JSONP. This is irreverent since the issue is already solved. Pls close this.

**Comment by domoritz** [comment]
I added a link to http://idl.cs.washington.edu/projects/lyra/ to the repository. There is a link to the demo below the abstract.

**Comment by arvind** [comment]
Thanks @sarathsaleem, good call on adding a link to the readme. And agreed on JSONP, I'm not particularly happy with the proxy.php method, and we should think about supporting JSONP with Vega. 

@domoritz, I didn't see a commit from you in the lyra repo? I updated README.md, did you update somewhere else?

**Comment by domoritz** [comment]
I added a link next to the repo title. 

![screen shot 2015-01-11 at 20 27 16](https://cloud.githubusercontent.com/assets/589034/5698967/4765bd68-99d0-11e4-90ea-486ff909d0b3.png)

**Comment by arvind** [comment]
Oh perfect! That's a great place to include it too. Thanks :)
