### ISSUE TITLE
Tooltip for long data field names

### ISSUE THREAD

**Issue by waxlamp** [uwdata/lyra#218]
The data table view is smart enough to cut off long field names with an ellipsis. However, it would be nice to hover over a long field name and get a tooltip displaying the full name.

**Comment by arvind** [comment]
This is incorporated into Lyra 2's new data table :) 
![the_lyra_visualization_design_environment](https://cloud.githubusercontent.com/assets/42262/13036335/85d94a14-d319-11e5-9bb2-577d7a42a4a7.png)
