### ISSUE TITLE
Typing formula with spaces for readability causes issues

### ISSUE THREAD

**Issue by Stephen-McDaniel** [uwdata/lyra#223]
Typing a formula with spaces for readability causes the cursor to jump to the beginning of the line and disables effective editing of formulas. 

For example, typing this works (Year is dragged from the data for each): 
Year==1810?"High":""

This causes the issue:
Year == 1810 ? "High" : ""

**Comment by arvind** [comment]
As we gear up for work on Lyra 2, tracking this issue as part of a new expressions UI in #230.
