### ISSUE TITLE
Support line marks

### ISSUE THREAD

**Issue by arvind** [uwdata/lyra#226]
Lyra 2 should support Vega's `line` mark type. This will involve creating:
- [ ] an primitive mark class.
  - What should the default (pre-data-binding) result be? Lines require some backing data. Vega offers rule marks but they can only be horizontal/vertical. 
  - Would be useful to use line marks to annotate things, so perhaps each line mark should instantiate a data source? Perhaps we can extend Vega or Vega-scenegraph to support arbitrary rules. Or, perhaps we produce a `path` mark? 
  - Lower priority: supporting line endpoints (arrowheads). Not natively supported in Vega but we can use reactive geometry to create a triangle symbol mark after the "line" mark.
- [ ] a manipulators transform class
- [ ] property inspector
- [ ] test cases for rules

We should strive to reuse infrastructure with area marks (#226).

**Comment by deathbearbrown** [comment]
Throwing the Vega docs in there for marks:
https://github.com/vega/vega/wiki/Marks

**Comment by arvind** [comment]
Initial support for line marks is now available. Will open additional issues to handle bugs+functionality (e.g., drawing a line out as an annotation).
