### ISSUE TITLE
Data Import UI

### ISSUE THREAD

**Issue by arvind** [uwdata/lyra#235]
To be truly useful to a broad community of users, Lyra 2 should make it as easy as possible to import data (JSON, CSV, TSV initially). Voyager took some good steps in this direction, and it would be great to extend this further. 
- [x] Import example datasets.
- [x] Import from URL.
- [x] Import from filesystem drag/drop or copy/paste (particularly copy/paste of spreadsheet/tabular data).
- [ ] Import from Google sheets, Dropbox, gist, etc.
- [x] Enter tabular data

Some thoughts on import:
- Users should be able to change inferred data types, but this should likely be a secondary UI concern (e.g., toggling between types by clicking them on field hover in the data table).
- Multiple data pipelines may be created from the same data source. This operation should be quick, and should share the backend model to reduce load latency and memory footprint.

**Comment by arvind** [comment]
Woo hoo, done via #392 and #393! Thanks @AnjirHossain!!

**Comment by maliky** [comment]
I'm very sorry to reopen that issue on data import but in my ignorance I cannot understand why thoses data urls ([1](https://raw.githubusercontent.com/maliky/images/master/data_head50_3_190930T0550.rec.json) an [2](https://raw.githubusercontent.com/maliky/images/master/data_head50_4_190930T0610.rec.json)) url data will not load on [lyra](https://idl.cs.washington.edu/projects/lyra/app/)  will they are fine for [voyager](https://vega.github.io/voyager/)  

I'm really not familiar with web technologies. But could it be a CORS problem ?
