### ISSUE TITLE
Add code coverage reporting

### ISSUE THREAD

**Issue by kadamwhite** [uwdata/lyra#251]
Code coverage should be computed when tests are run, and that should be exposed via Travis.

**Comment by arvind** [comment]
We use `istanbul` in the other Vega projects. We had experimented with coveralls.io in the past, but found that it didn't reliably recalculate coverage all the time.

**Comment by kadamwhite** [comment]
+1 for istanbul, I've used it on other projects and found it to be the most straight-forward option.

**Comment by arvind** [comment]
We have `npm run cover` with b6193e1. Thanks @kadamwhite!
