### ISSUE TITLE
Update build process

### ISSUE THREAD

**Issue by kadamwhite** [uwdata/lyra#254]
GH issue to track https://bocoup.atlassian.net/browse/LYRA-252
- [x] Move script build process to [Webpack](https://webpack.github.io/) (done in #255) [LYRA-258](https://bocoup.atlassian.net/browse/LYRA-258)
- [x] Add editorconfig file (done in #258) [LYRA-259](https://bocoup.atlassian.net/browse/LYRA-259)
- [ ] Add an `npm start` script to run a local dev server [LYRA-260](https://bocoup.atlassian.net/browse/LYRA-260)
- [ ] Add [eslint](http://eslint.org) for code linting [LYRA-261](https://bocoup.atlassian.net/browse/LYRA-261)
- [ ] Remove unused package scripts [LYRA-262](https://bocoup.atlassian.net/browse/LYRA-262)
- [ ] Remove unused NPM dependencies [LYRA-263](https://bocoup.atlassian.net/browse/LYRA-263)

**Comment by arvind** [comment]
I believe these are all done now. Thanks @kadamwhite!
