### ISSUE TITLE
Personas

### ISSUE THREAD

**Issue by deathbearbrown** [uwdata/lyra#256]
I have 2 personas so far out of three.
- [x] Student
- [x] Senior Data Vis Engineer
- [x] Journalist

---

**Role:**  Task Oriented

**Name:** Padma Dawn

**Quote:**

> " This paper is due tomorrow... I wonder if I can draw these charts in by hand. Does anyone have crayons? "

### Background:

**Age:** 20<br>
**Location:** WA<br>
**Marital Status:** Single<br>
**Kids:** No<br>
**Occupation:** Undergrad Student<br>
**Education:** getting a BS
### Characteristics
- Curious
- Non-technical
- Stressed
- Easily overwhelmed
## Goals/Needs
- Needs to create nice looking, polished data visualizations to accompany her research papers.
### TECH KNOWLEDGE

██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░<br>
Hello World                                                                                        expert
### OPEN SOURCE CONTRIBUTIONS

██████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░<br>
What's github?                                                                              Constantly Contributing
### DATA VIS KNOWLEDGE

████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░<br>
pie chart?                                                                                    invented charts
## About

Padma is a 3rd year student in College studying Statistics & Psychology.  She also helps in a lab as a research assistant.  She wants to add data visualizations to her term papers to show correlation of data she's collected, but doesn't have many good options when it comes to free tools to use as a student. She is overwhelmed by bad documentation and false starts with existing tools.

---

**Role:** The Tinkerer

**Name:** Jane Delany

**Image Credit:**
(taken from friend's twitter. Oops)
### Quote:

> "I love discovering new ways to explore data sets."

### Background:

**Age:** 28<br>
**Location:** LA<br>
**Marital Status:** Single<br>
**Kids:** No<br>
**Occupation:** Data Visualization Engineer<br>
**Education:** B.S.
### Characteristics
- Curious
- Helpful
- Experienced
- Passionate
### Goals/Needs
- Needs to be able to prototype data quickly to see if there are any correlations worth exploring that can't be achieved through pen & paper and aren't as time consuming as programming an entire app in D3.
### TECH KNOWLEDGE

██████████████████████████░░░░░░░░░░░░░░░░░░░░<br>
Hello World                                                                                         expert
### OPEN SOURCE CONTRIBUTIONS

█████████████████████████████░░░░░░░░░░░░░░░<br>
What's github?                                                                                Constantly Contributing
### DATA VIS KNOWLEDGE

████████████████████████████████░░░░░░░░░░░<br>
pie chart?                                                                                      invented charts
## About

Jane is an engineer who builds her own data visualizations using libraries like D3 and p5.js.  She has a github account. She contributes to libraries she uses and also open-sources her own code.

Her job is as a consultant and she is often on short deadlines where she needs to come up with an interesting way to look at data sets given to her.  She prototypes in paper and code.  She wants to see applications in action before she decides to use them.

---

**Role:** The Data Novice

**Name:** Terry James
### Quote:

> "I think visualizations will give depth to my article."

### Background:

**Age:** 34<br>
**Location:** MA<br>
**Marital Status:** Married<br>
**Kids:** No<br>
**Occupation:** Journalist<br>
**Education:** B.S. Communications
### Characteristics
- Passionate
- Eloquent
- Not technical 
- Researcher
### Goals/Needs
- Create a data visualization to accompany an article that proves the point he is trying to make in an engaging way.
### TECH KNOWLEDGE

██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░<br>
Hello World                                                                                         expert
### OPEN SOURCE CONTRIBUTIONS

░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░<br>
What's github?                                                                                Constantly Contributing
### DATA VIS KNOWLEDGE

███████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░<br>
pie chart?                                                                                      invented charts
## About

Terry is a journalist for the Boston Globe.  He is always researching new stories and heavily sources his work. He has little background in statistics and while he's adept at uncovering resources, he doesn't know what bad data looks like.  He is not sure which chart to use to enhance his story with data.

**Comment by iros** [comment]
First 2 look good to me and I left comments on the journalist persona in the respective issue #264.

**Comment by arvind** [comment]
Done!
