### ISSUE TITLE
Journey Maps

### ISSUE THREAD

**Issue by deathbearbrown** [uwdata/lyra#257]
**What is a journey map?**

A journey map is an exercise you can do after you created your personas to walk them through a task they need to complete that may involve your application.   The reason we do this is because it exposes what is very necessary to make your app useable for people. Just saying something as simple as "Oh I made this thing, how do I show it to my team?" reveals that sharing should be a core component of your app and might need to get bumped up priority-wise. 

Here are the Journey Maps for The Task Oriented and The Tinkerer personas. These are screenshots from trello. I will work ok a template for markdown. 

![screen shot 2016-02-26 at 8 51 34 am](https://cloud.githubusercontent.com/assets/607541/13359144/7ea4b88a-dc67-11e5-8df2-57577a27d085.png)
![screen shot 2016-02-26 at 8 48 27 am](https://cloud.githubusercontent.com/assets/607541/13359145/7ec118f4-dc67-11e5-8c41-b07ae7ae0f98.png)

**Comment by deathbearbrown** [comment]
Here's a Contributor & Maintainer Journey. We need to make sure there's project maintainer interaction in certain parts to make a successful experience. 

![screen shot 2016-02-26 at 10 41 54 am](https://cloud.githubusercontent.com/assets/607541/13361778/981ccbb4-dc75-11e5-86e9-d72c745e1b93.png)

**Comment by arvind** [comment]
@deathbearbrown, when you get a chance, could you publish these to the `gh-pages` branch like you did with the personas?

**Comment by arvind** [comment]
Done with 7b55501. Thanks @deathbearbrown!
