### ISSUE TITLE
Journalist Persona (& interview notes)

### ISSUE THREAD

**Issue by deathbearbrown** [uwdata/lyra#264]
I interviewed a Data Vis engineer who works for a newspaper about the frustrations a non-technical journalist using a data vis tool would have. 

One main concern is giving a tool to a journalist who does not have any statistical training.
### How to represent data
- can make nice graphs that don't have the right information
- What charts to use for different types of data
  - what to use if you are showing change over time
  - what to use if you are showing correlation etc
- Giving suggestions of charts:  barchart, bubble charts, treemaps, timelines
### Data
- aren't aware of what bad data is
  - that you can't have data that's full of null values and expect it to make anything
  - knowing when an outlier is a mistake vs a story they should look into
  - knowing what realistic scales are for their data
  - accounting for things like inflation or population before working with the data
- being able to understand the data they are looking at
  - what does each column header mean mean
  - where it came from and how it was collected
### High level information

Problems typically aren't things like "don't use this color for accessibility reasons"  they are more fundamental like "what question do you want to answer with this visualization?"
- making sure it conveys useful information
- making sure it is conveying the RIGHT information

Suggests having default/minimum settings for styles and advanced menus for customization.

---

**Role:** The Data Novice

**Name:** Terry James
### Quote:

> "I think visualizations will give depth to my article."

### Background:

**Age:** 34<br>
**Location:** MA<br>
**Marital Status:** Married<br>
**Kids:** No<br>
**Occupation:** Journalist<br>
**Education:** B.S. Communications
### Characteristics
- Passionate
- Eloquent
- Not technical 
- Researcher
### Goals/Needs
- Create a data visualization to accompany an article that proves the point he is trying to make in an engaging way.
### TECH KNOWLEDGE

██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░<br>
Hello World                                                                                         expert
### OPEN SOURCE CONTRIBUTIONS

░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░<br>
What's github?                                                                                Constantly Contributing
### DATA VIS KNOWLEDGE

█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░<br>
pie chart?                                                                                      invented charts
## About

Terry is a journalist for the Boston Globe.  He is always researching new stories and heavily sources his work. He has little background in statistics and while he's adept at uncovering resources, he doesn't know what bad data looks like.  He is not sure which chart to use to enhance his story with data.

**Comment by iros** [comment]
I think this is mostly accurate, though I'd say some journalists have a bit more knowledge of data visualization existing. So, probably like, 1/3 of the way forward? You kinda need to know what your graphs are. This is targeting an audience of journalists who already know enough about data to assemble it and probably study it somehow for some kind of pattern (maybe with excel or google spreadsheets?)

**Comment by deathbearbrown** [comment]
updated!

**Comment by arvind** [comment]
@deathbearbrown When you get a chance, could you migrate this to the `gh-pages` branch as well? Thank you :)

**Comment by arvind** [comment]
Done with 7b55501. Thanks @deathbearbrown!
