### ISSUE TITLE
Integrate CSS build with Webpack

### ISSUE THREAD

**Issue by kadamwhite** [uwdata/lyra#268]
SCSS compilation currently exists outside the purview of Webpack, which means CSS changes will not be accounted for the same way as 

This issue is a backlog item, but it encompasses EITHER
- [ ] Determining a structure for component stylesheets that will accommodate hot module replacement
- [ ] Moving SCSS compilation into Webpack
- [ ] Configuring the application for hot module replacement

(preferred) OR
- [ ] Determine a structure for component stylesheets exclusive of HMR
- [ ] Move SCSS compilation into webpack
- [ ] Configure the dev server to reload when SCSS changes

LYRA-268

**Comment by arvind** [comment]
I (think?) this has been handled as part of #363? @kadamwhite could you re-open if there's still something left to do here?
