### ISSUE TITLE
Extend and refine JSDoc coverage

### ISSUE THREAD

**Issue by kadamwhite** [uwdata/lyra#269]
This issue tracks overflow from #263
- [ ] Use class names instead of `{Object}` in `@return` statements where appropriate
- [ ] Avoid non-descriptive or one-letter variable names (with the conventional exception of `for` loop iterators)

Three key undocumented areas (list ported from the earlier PR):
- [ ] `model/signals`
- [ ] `model/rules`
- [ ] `model/primitives/marks/manipulators`

this raises
- [ ] Identify (as a group) the JSDoc convention that will be used to document extensions of `Mark`s

**Comment by arvind** [comment]
All of the above have been documented since this issue was opened. Thanks all!
