### ISSUE TITLE
Document a basic interface "smoke test"

### ISSUE THREAD

**Issue by kadamwhite** [uwdata/lyra#276]
@arvind this one's for you: When you test out the interface _at the present moment_, can you document the interactions you run through? Having a script we could follow from your point of view wouldn't replace randomly clicking around and seeing what breaks, but I suspect you account for interactions that I might not think of (like the alternate direct interaction modes) when you are testing whether a change introduced a regression.

Documenting this process can serve as the basis for integration tests, when/if we get to that stage

**Comment by arvind** [comment]
1. `rm -Rf node_modules, build`
2. `npm install`
3. `npm run build`
4. Load the app and test:
   1. Did the visualization render correctly with a symbol mark and rect mark?
   2. Did the react components initialize correctly?
   3. Can I select the symbol mark and rect mark -- do the handles appear around the mark instance, do the react components update accordingly (expand the layers list, show the property inspector).
   4. When selected, can I resize + move the marks -- using the handles, dragging the mark on the canvas, or changing values in the property inspector.
   5. Once I start dragging a data field, do cyan channel dropzones appear? If I drag near them, do I see the bubble cursor and is a corresponding dropzone selected?
   6. Does dropping the fields w/bubble cursor selection (i.e., while not directly over a dropzone) trigger production rule evaluation -- i.e., are corresponding scales+guides created, and does the mark's property now have a data binding?

**Comment by kadamwhite** [comment]
Thanks @arvind ! The remaining TODO for this is to capture it in documentation, which @deathbearbrown or I will do as time permits. In the meantime I will use these steps to validate any new PRs that come in.
