### ISSUE TITLE
Switch from Dropdowns to Buttons for some text properties

### ISSUE THREAD

**Issue by kadamwhite** [uwdata/lyra#283]
### Description of requested feature

Lyra 1 supported button-based interaction for certain properties of text marks:
![image](https://cloud.githubusercontent.com/assets/442115/13646120/0a0a4262-e5fc-11e5-85a3-e7b29cf9b2a6.png)
![image](https://cloud.githubusercontent.com/assets/442115/13646125/0f5f0c2a-e5fc-11e5-82aa-03f641807e03.png)

These functions have been implemented in #281 using a select menu:

![image](https://cloud.githubusercontent.com/assets/442115/13646172/3d61dde6-e5fc-11e5-9b27-96db0fef8ad7.png)

We should create a property inspector component that permits setting these properties through buttons, rather than dropdowns, to improve the current Lyra 2 user experience and achieve parity with the Lyra 1 UI.
### Why this feature is important to you

Select menu dropdowns are a sub-par user experience for a number of reasons, and a toggle button (for bold or italic) or multiple graphical buttons (for e.g. alignment or baseline) more closely maintain the paradigm established by popular software like word processors.

**Comment by nikhilkhanna** [comment]
So I've gotten this all implemented functionality-wise; however, Font Awesome does not have the images that the previous version of Lyra used for vertical alignment and from the old version of Lyra I could only find png versions of those assets, not the svg ones. Are there any other svg assets that would work well in place of the old vertical alignment assets?

**Comment by arvind** [comment]
You might try https://thenounproject.com to see if there are icons there that match. We've used a handful of noun project icons, and have commented out the attribution text in the SVG (which we'll pull out and include in our "about" dialog at the end).

**Comment by nikhilkhanna** [comment]
I've also noticed that, at least how it is now, setting the alignment of the text to, say "top" actually moves the text down and setting it to "bottom" moves the text up. Similarly setting alignment "left" moves the text to the right and setting alignment "right" moves the text to the left. Is this behavior as intended or should I correct this?

**Comment by arvind** [comment]
Addressed w/#402. Re: how the text appears to shift, that's right -- the alignment (horizontal + vertical) determine how the (x, y) coordinates of a text mark position it. By default, with center+middle alignment, the (x, y) are the center of the text mark. Switching to "top" will make the text mark shift down since the (x, y) now determine the center-top coordinate. Nice work @nikhilkhanna!
