### ISSUE TITLE
Change "pipelines" dropdown in Inspector to a static label

### ISSUE THREAD

**Issue by kadamwhite** [uwdata/lyra#303]
From @arvind re: the purpose of the Pipeline dropdown in the Inspector, which currently has no effect:

> The pipelines drop down was left over from Lyra 1 and I'm ambivalent about whether it should exist or not. Basically it allows you to change the pipeline that a mark draws from. But this almost always will break the mark/require re-binding properties. So maybe it's best to just display the pipeline as a label rather than allow users to switch it
> 
> However what ​_was_​ working was that the correct pipeline name would appear in the drop down after binding. Changing the drop down did not work

The current plan is to convert this pipeline dropdown to a static label, indicating which pipeline the data in that mark came from.

**Comment by arvind** [comment]
Done with the #337!
