### ISSUE TITLE
Utilize post-processor to add vendor prefixing

### ISSUE THREAD

**Issue by kadamwhite** [uwdata/lyra#313]
From #311 : The work of adding vendor prefixes to relevant CSS properties is grunt-work that can and should be offloaded from a human style author to an automated system, as a post-processor or a loader within Webpack. It looks like [postcss/autoprefixer](https://github.com/postcss/autoprefixer) may be relevant to this effort.

**Comment by arvind** [comment]
Done with 896a363.
