### ISSUE TITLE
Refactor map*ToProps functions to improve performance

### ISSUE THREAD

**Issue by kadamwhite** [uwdata/lyra#335]
In the code snippet,

``` js
function mapStateToProps(store) {
  return {
    val: store.getState().val
  };
}

module.exports = connect(mapStateToProps)(React.createClass({
  render: function() {
    return (<p>{this.props.val}</p>);
  }
}));
```

`mapStateToProps` will run on _every_ store update; `render` will only run when the `.val` which is assigned to props changes.

We can use this knowledge to make smarter decisions about how we write our `mapStateToProps` method: for example, any code that derives or iterates on the results of store data should go into a method on the component, _not_ in `mapStateToProps`, because there is no need to compute a generated value unless the original value has changed.

Making these updates across the app should resolve the lag we experience when dragging objects on the stage.

**Comment by arvind** [comment]
I can't find the specific PR but I believe this has been taken care of. A quick grep through the codebase doesn't reveal any `toJS` calls being made within `mapStateToProps`.
