### ISSUE TITLE
Decision: Naming standard for actions

### ISSUE THREAD

**Issue by kadamwhite** [uwdata/lyra#349]
It is possible in a redux application for there to end up being a _lot_ of action creator methods, each with their own "type" string. Because action creators are just functions, they can be exposes as properties on objects or as modules in and of themselves. We do a bit of both; further, we're inconsistent in how we name the action files and methods. Here's our file list mapped to the action creators defined by those files, as the functions are named in each file:
- createScene.js
  - createScene
- expandLayers.js
  - expandLayers
- markDelete.js
  - deleteMark
- primitiveActions.js
  - addMark
  - updateMarkProperty
  - setParent
- removeLayers.js
  - removeLayers (unused)
- ruleActions.js
  - addScaleToGroup
  - addAxisToGroup
  - addLegendToGroup
  - setProperty
  - disableProperty
  - resetProperty
- sceneClear.js
  - sceneClear
- selectMark.js
  - selectMark
- selectPipeline.js
  - selectPipeline
- signalInit.js
  - signalInit
- signalSet.js
  - signalSet
- signalSetStreams.js
  - signalSetStreams
- signalUnset.js
  - signalUnset (unused)
- toggleLayers.js
  - toggleLayers
- vegaInvalidate.js
  - vegaInvalidate
- vegaParse.js
  - vegaParse

I'd like to propose that we establish a guideline for how actions should be grouped in files, named, and mapped to types.

One option would be to group action creators by the store property that they are _most_ associated with, e.g.

```
markActions
  addMark
  deleteMark
signalActions
  initSignal
  setSignal
```

If they're namespaced like this, either by having one file for all markActions which exposes its creators as properties, or by having markActions be a folder with functions-as-modules inside it, the names of the action modules/methods themselves could be kept fairly English-language-ordered ('addMark' instead of 'markAdd').

The contrasting approach would be to have a flat actions directory where each file is named to group like actions next to each other:

```
markAdd
markDelete
signalInit
signalSet
```

There's probably middle ground here too. Whatever scheme is adopted, we should also look at the list of types which support these actions:
- CREATE_SCENE
- PRIMITIVE_ADD_MARK
- PRIMITIVE_DELETE_MARK
- PRIMITIVE_SET_PARENT
- PRIMITIVE_UPDATE_PROPERTY
- VEGA_INVALIDATE
- VEGA_PARSE
- SIGNAL_INIT
- SIGNAL_SET
- SIGNAL_SET_STREAMS
- SIGNAL_UNSET
- RULES_ADD_SCALE_TO_GROUP
- RULES_ADD_LEGEND_TO_GROUP
- RULES_ADD_AXIS_TO_GROUP
- RULES_SET_PROPERTY
- RULES_DISABLE_PROPERTY
- RULES_RESET_PROPERTY
- PIPELINE_SELECT
- EXPAND_LAYERS
- REMOVE_LAYERS
- SELECT_MARK
- TOGGLE_LAYERS

and document how these files and properties should be named in a README.md in each of the actions and constants directories.

**Comment by arvind** [comment]
Done with #379. Actions are now grouped by the object they act on, with action types defined there as well and marshaled in a registry. Thanks @kadamwhite!
