### ISSUE TITLE
UI: Additional Dropzone Types

### ISSUE THREAD

**Issue by deathbearbrown** [uwdata/lyra#358]
Right now we support X and Y axis.

![dropzones](https://cloud.githubusercontent.com/assets/607541/14691521/7e16ec70-0706-11e6-8e5f-b4cfa5159866.gif)

We could also expand to:
- Color
- Stroke
- Opacity
- shape (for symbols)

What would it look like on the canvas if extended to support these other types. 

Options:  show advanced interface on modifier keypress, like SHIFT + DRAG currently shows the dropzones for height & width.

**Comment by deathbearbrown** [comment]
haha it's all but impossible to screenshot this well
![screen shot 2016-04-21 at 9 10 32 am](https://cloud.githubusercontent.com/assets/607541/14717086/a977aa0a-07a4-11e6-8162-3bef03f448ad.png)

For Fill and stroke, I thought we could add something like this on drag over in addition to the arrows.  But my concern would be making sure that the groups for each zone wouldn't override each other.

**Comment by deathbearbrown** [comment]
For symbols... Right now we have a drop down to change the type.  Do know the use case where you'd want to drag and drop a symbol type onto the mark vs selecting the mark and updating it via the inspector?

**Comment by arvind** [comment]
Yes, consider the shape of a symbol in a scatterplot to be determined by data like so:

![shapescatterplot](https://cloud.githubusercontent.com/assets/42262/14717326/c40b272e-07a5-11e6-9c96-56912c828e66.png)

**Comment by deathbearbrown** [comment]
Note:  Attaching data to symbol, stroke, fill or opacity does not let you pick individual values for that data.  EG, I can't choose to make Japan a circle in the above example.

**Comment by deathbearbrown** [comment]
Here's an example of an interaction I find to be a little janky in lyra2 currently:
![annoying](https://cloud.githubusercontent.com/assets/607541/14718195/0eaf7376-07aa-11e6-80a7-e4d15d717bd3.gif)
- I make a rect mark and select it
- drag data onto an axis
- the selected mark jumps to the bottom of the screen
- now I have to drag data all the way down to the bottom of the screen and the dropzone is smaller.

**Comment by deathbearbrown** [comment]
BEHOLD, the worst sketch
![fullsizerender 2](https://cloud.githubusercontent.com/assets/607541/14718436/8326a62e-07ab-11e6-800b-dbc4eef4644f.jpg)

The Overlay would always be large and take up the whole visible scene. Or at least always be consistently located. 
You could build it in Lyra and not have to draw the dropzones in vega.

**Comment by deathbearbrown** [comment]
ISSUES with the above:
How do you make it very clear to the user which mark they currently have selected?

**Comment by deathbearbrown** [comment]
![img_4377](https://cloud.githubusercontent.com/assets/607541/14720649/58763ad2-07b7-11e6-9b89-e5e502ebcd6d.JPG)

What if on drag the dropzone box always had a visual connection to the mark?  That way you can maintain the consistent size of the dropzone.  Show the connection to the mark.  And if the mark moves on the scene, it still shows it's connection?

**Comment by kadamwhite** [comment]
> - now I have to drag data all the way down to the bottom of the screen and the dropzone is smaller.

I wonder what happens if you unbind data from a line or area mark... Not at a computer to try, but I suspect that it collapses to a single point and the drop handles become all but unusably small.

**Comment by deathbearbrown** [comment]
@kadam the test was on rect marks and it's because it keeps the first generated mark selected, which has moved to the bottom of the screen.

**Comment by kadamwhite** [comment]
@deathbearbrown Oh I understood that, I was just speculating that we were overlooking an arguably more serious issue with other types of marks:
![area issue](https://cloud.githubusercontent.com/assets/442115/14745289/a310e5ee-0878-11e6-8107-e051682fc8fc.gif)

**Comment by deathbearbrown** [comment]
@kadamwhite  can you put that in #359, since this is for dropzone types

**Comment by deathbearbrown** [comment]
## Additonal Dropzones

Each mark has specific additional dropzones we want to have on drag other than the spatial ones that already exist.
- LINE: 
  - stroke 
- RECT:
  - stroke
  - fill
  - opacity
- SYMBOL:
  - symbol
  - stroke
  - fill
  - opacity
- AREA:
  - stroke
  - fill
  - opacity
- TEXT:
  - color (fill)
  - text

There are 2 dragging states that can be done in Lyra2, regular **drag** and **shift drag**.

On **DRAG** show:
- FILL (or color for text)
- SYMBOL (only for symbol)
- Text (only for text)
- X & Y Axis

On **SHIFT + DRAG** show (Alternative Channels):
-  OPACITY (where fill was) 
-  STROKE (where symbol is but for all marks) 
-  alternative spatial channels for x & y axis

#### Current bugs dropzones as they are now:
- Adding data to a mark like RECT or SYMBOL can cause the selected mark to jump around the scene. 
  - Solution: reselect the mark closest to the last selected mark
- a user can move a mark off the scene. 
  - Solution: do not allow position to be set off the scene
- a user can move a mark partially off the scene: 
  - Solution: require padding in scene, do not allow mark to be positioned off the scene or inside this padded area.
- adding data to any mark will change the dropzone length.  
  - Solution: a minimum dropzone length must be set.
- bug with group layering & fill makes it so you can't drop onto things that have a group layered on top of them
  - Solution: we have an issue for this to not set a fill value on groups and only set fill:transparent when selected (or a mark inside the group container is selected) 

### Some Gotchas with the new design:
- Overlapping dropzones have the potential to be buggy.  Make sure the dropzones implementation doesn't overlap so that data can get dropped on the right area
- When adding new marks to the screen they will need to be positioned just so that you can show the dropzones without them falling outside of the canvas.  This is an issue for most marks.
- New marks should have a standard size they start as, right now they are all sorts of different sizes
- area and line marks starting state is a bit broken. You can't move them around the canvas.

**Comment by deathbearbrown** [comment]
A mockup of DRAG for a RECT.  Please ignore the colors.
![drag_rect](https://cloud.githubusercontent.com/assets/607541/14753795/6b0d7306-088c-11e6-9fc2-0f269c48b778.png)

A Mockup of SHIFT DRAG for RECT
![shift_drag_rect](https://cloud.githubusercontent.com/assets/607541/14753805/7ec69990-088c-11e6-8375-1901d78545c6.png)

**Comment by deathbearbrown** [comment]
The dropzone should have a min-size that it can be, so that if a user make a mark very tiny, you don't lose the drop zones.

For example:
![ittybitty](https://cloud.githubusercontent.com/assets/607541/14754056/d1f6c8fa-088d-11e6-839c-6a2d6d24f00a.png)

Also I put the FILL and OPACITY dropzones outside the mark so that we can control their size and always be able to label the zones, but still let the user modify their mark to whatever size they need.

**Comment by deathbearbrown** [comment]
There should also be a MAX size the drop overlays can be, which would be still within the constraints of the canvas.  If a user makes a mark so big that it almost fills the canvas, the dropzones would show up inside the mark like this:
![max](https://cloud.githubusercontent.com/assets/607541/14754682/c890f2e6-0891-11e6-9946-92d42717581c.png)

**Comment by deathbearbrown** [comment]
Here are some mockups for other marks:
![drag_line](https://cloud.githubusercontent.com/assets/607541/14755931/8c49345c-089a-11e6-8ef4-b752c247ecfd.png)

Line after you've bound data to one axis:
![screen-shot-2016-04-22-at-2 51 59-pm](https://cloud.githubusercontent.com/assets/607541/14755937/9a97ce10-089a-11e6-9d0d-df994fdc7e3b.png)

Area:
![drag_area](https://cloud.githubusercontent.com/assets/607541/14755939/a2b9a708-089a-11e6-9466-fb5fb8f9219d.png)

**Comment by deathbearbrown** [comment]
Does this look ok for symbol dropzones?
![symboldrag](https://cloud.githubusercontent.com/assets/607541/14756136/efa9bd5e-089b-11e6-9559-2dc9ba04e780.png)

For each symbol type (triangle, cross, diamond, etc) create dropzones in the shape of that shape

**Comment by deathbearbrown** [comment]
NOTE: don't show the drag handles when showing the dropzone.  Don't believe the lies in my mockups!

**Comment by deathbearbrown** [comment]
Here's an issue:
You bind data to one axis and the marks are rendered in an area that if you put the min dropzone around the mark, it might not fit.  

This mockup is kind of an exaggeration.  Note that the min dropzone size you decide on need to be able to fit labels in them. 
![anissue](https://cloud.githubusercontent.com/assets/607541/14756452/3e1f122a-089e-11e6-93b3-b3668c23fc05.png)

**Comment by arvind** [comment]
Done with #396.
