### ISSUE TITLE
Module build failed: ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by aliabbasjp** [uwdata/lyra#361]
on doing npn run build from the main readme page here  I get following error:
`
/lyra$ npm run build

> lyra@2.0.0 build /code/lyra
> webpack -d

Hash: 1fd60819d724d01dce96
Version: webpack 1.13.0
Time: 7369ms
           Asset       Size  Chunks             Chunk Names
      js/lyra.js    2.77 MB       0  [emitted]  lyra
    js/vendor.js    2.02 MB       1  [emitted]  vendor
  js/lyra.js.map    3.26 MB       0  [emitted]  lyra
js/vendor.js.map    2.31 MB       1  [emitted]  vendor
    ./index.html  598 bytes          [emitted]
   [0] multi vendor 88 bytes {1} [built]
    + 569 hidden modules

ERROR in ./~/css-loader!./~/sass-loader!./src/scss/app.scss
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/code/lyra/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/code/lyra/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:79:21)
    at processCss (/code/lyra/node_modules/css-loader/lib/processCss.js:198:5)
    at Object.module.exports (/code/lyra/node_modules/css-loader/lib/loader.js:24:2)
 @ ./src/scss/app.scss 4:14-120
Child html-webpack-plugin for "index.html":
        + 1 hidden modules
`

**Comment by kadamwhite** [comment]
Does `npm start` work, or does that give you the same error? Would you be able to share your node version, NPM version and operating system?

**Comment by aliabbasjp** [comment]
@kadamwhite 
yes npm start does NOT work:

npm version
{ lyra: '2.0.0',
  npm: '3.8.3',
  ares: '1.10.1-DEV',
  http_parser: '2.6.2',
  icu: '56.1',
  modules: '47',
  node: '5.10.1',
  openssl: '1.0.2g',
  uv: '1.8.0',
  v8: '4.6.85.31',
  zlib: '1.2.8' }

uname -a
Linux Data-Server 4.2.0-35-generic #40~14.04.1-Ubuntu SMP Fri Mar 18 16:37:35 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kadamwhite** [comment]
@aliabbasjp `npm run build` and `npm start` are both working for me on OSX with Node v5.10.1, which I see you are using as well. I'll try to get an ubuntu environment spun up to test but this initially has me stumped.

_[edited b/c I missed Node in the output of npm version]_

**Comment by arvind** [comment]
Just want to also double check, @aliabbasjp, that you've run `npm run install`? Thanks!

**Comment by aliabbasjp** [comment]
@arvind @kadamwhite 
again running npm install as root:

```

# npm install

> canvas@1.3.12 install /code/lyra/node_modules/canvas
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/code/lyra/node_modules/canvas/.node-gyp"
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.2.0-35-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /code/lyra/node_modules/canvas
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:canvas@1.3.12 canvas@1.3.12 install: `node-gyp rebuild`
npm WARN install:canvas@1.3.12 Exit status 1
npm WARN optional Skipping failed optional dependency /karma/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm WARN optional Skipping failed optional dependency /nodemon/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm WARN optional Skipping failed optional dependency /webpack/watchpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11

```

**Comment by aliabbasjp** [comment]
without root : 

```
$ npm install

> canvas@1.3.12 install /code/lyra/node_modules/canvas
> node-gyp rebuild

Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.2.0-35-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /code/lyra/node_modules/canvas
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:canvas@1.3.12 canvas@1.3.12 install: `node-gyp rebuild`
npm WARN install:canvas@1.3.12 Exit status 1
npm WARN optional Skipping failed optional dependency /karma/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm WARN optional Skipping failed optional dependency /nodemon/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm WARN optional Skipping failed optional dependency /webpack/watchpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
```

**Comment by kadamwhite** [comment]
@aliabbasjp Does `npm run build` still fail after that `npm install`? (sudo should not be required). The Cairo warning is noisy but I do not believe we explicitly depend on it anywhere.

**Comment by aliabbasjp** [comment]
@kadamwhite  I had resolved the problem after installing cairo dependency

**Comment by kadamwhite** [comment]
@aliabbasjp great! Glad to hear it.
