### ISSUE TITLE
Lyra Vega Exports do not work with Vega Scaffold

### ISSUE THREAD

**Issue by hendrikunger** [uwdata/lyra#366]
I am reporting a bug

**Expected Behavior**
I feel like I should be able to use exports from Lyra directly with the Vega scaffold.
**Actual Behavior**
The browser command line logs the error: "Uncaught TypeError: Cannot read property 'temp' of undefined" where temp is one of the keys in the data field. One needs to remove "data." in the field declarations in the scales and marks sections of the vega code, e.g.

```
  "scales": [
    {
      "type": "linear",
      "points": true,
      "nice": true,
      "padding": 0,
      "zero": true,
      "name": "pipeline_1_scale_6",
      "domain": {
        "data": "pipeline_1",
        "field": "data.temp"  <------------------------------------------- Remove "data."
      },
      "inheritFromGroup": false,
      "range": "height",
      "lyra.displayName": "Y"
    }
  ]
```

**Steps to reproduce behavior**
Use temps dataset in Lyra, create a line diagramm with "date" on the x axis and "temp" on the y axis.
Export in Lyra with inlined data option.
Use the resulting json file in the [Vega scaffold](https://github.com/vega/vega/wiki/Runtime).

**Comment by arvind** [comment]
Hi @hendrikunger, thanks for filing the issue! The deployed version of Lyra uses the previous major release of Vega. So, to embed a Lyra export in a webpage, you'll either need to use [an older version of Vega](https://github.com/vega/vega/blob/v1.x/vega.min.js) or upgrade the exported specification [according to these instructions](https://github.com/vega/vega/wiki/Upgrading-to-2.0). 

We're currently working on a new version of Lyra, with a fully rewritten codebase, that uses Vega 2. Thus, exported specifications will work with the Vega scaffold directly. Work on this branch is still ongoing, but we're optimistic about having a production ready release over the next few months!
