### ISSUE TITLE
Bug with delete marks and add marks

### ISSUE THREAD

**Issue by deathbearbrown** [uwdata/lyra#368]
**Expected Behavior**
- add 2 marks
- delete one
- add new mark & the mark will show up in the visualization side bar, the canvas & be exported

**Actual Behavior**
- add 2 marks
- delete one
- add new mark, 
  - inspector is there
  - doesn't show up on the canvas
  - not in visualization sidebar 
  - not in the export

This looks like a syncing issue, I am looking into it.

**Comment by deathbearbrown** [comment]
More bug updates:
- happens with primitives applied directly to the scene.  Primitives in a group can be deleted and re-added and it's NBD

**Comment by deathbearbrown** [comment]
@arvind good news, it is not a sync issue. The parent was just being passed as null from the toolbar react component :/ boo. That's why groups always worked because it was set up in a different react component. 
PR here #371

**Comment by arvind** [comment]
Fixed with #371, thanks @deathbearbrown!
