### ISSUE TITLE
New pipeline overwrites example pipelines

### ISSUE THREAD

**Issue by thSoft** [uwdata/lyra#439]
* Open an example visualization, e.g. http://idl.cs.washington.edu/projects/lyra/app/#?example=playfair
* Click New pipeline
* The second existing pipeline is overwritten by the newly created one
* Further new pipelines overwrite other existing pipelines sequentially

**Comment by jonathanzong** [comment]
Closed because it refers to the old version of Lyra. We plan to release Lyra 2 soon, thanks for your patience!
