### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by SgtPooki** [uwdata/lyra#440]
- [x] I am requesting a new feature

**Description of requested feature**
Add a LICENSE file to the repo

**Why this feature is important to you**
I cannot use this software for a project I'm working on unless it is using an appropriate license, and currently you don't have a license declared.

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project.
> 
> https://help.github.com/en/articles/licensing-a-repository#what-happens-if-i-dont-choose-a-license

**Comment by davidanthoff** [comment]
Let me second this, a license here would be very helpful.
