### ISSUE TITLE
Lyra v2 docs have been discovered by google

### ISSUE THREAD

**Issue by danyelf** [uwdata/lyra#444]
Note that http://vega.github.io/lyra/ has been indexed by google, and shows up as "vega lyra" in the top few hits. 

![image](https://user-images.githubusercontent.com/3173714/67436524-700ec000-f5a3-11e9-8760-55002b8743d5.png)

**Comment by jonathanzong** [comment]
Thanks for letting us know! We took down the unfinished docs.
