### ISSUE TITLE
fast-json-stable-stringify 

### ISSUE THREAD

**Issue by jonathanzong** [uwdata/lyra#449]
copied from https://github.com/vega/lyra/pull/447

Currently, Webpack fails at correctly compiling Vega-Lite's reference to fast-json-stable-stringify which is an ES6 import statement of a CommonJS module.

Pending a more thorough investigation/overhaul of our build system, we will need to dig into node_modules/vega-lite/src/util.ts and replace the import with an old-style CommonJS require:

const stableStringify = require('fast-json-stable-stringify');

**Comment by arvind** [comment]
Resolved with fd7c0ad7. I'd recommend `rm -rF node_modules` and then re-running `yarn` after your next `git pull`.
