### ISSUE TITLE
Bubble cursor breaks on hydrated spec

### ISSUE THREAD

**Issue by jonathanzong** [uwdata/lyra#452]
After loading a spec from file, the bubble cursor throws errors when trying to drop a field onto a channel.

I think this is possibly because after reload the group is selected by default instead of the mark? 

Would be cool longer term if the bubble cursor could shift between group and mark dropzones based on proximity instead of having to re-select one or the other.

To reproduce: load a spec from a file, then try to drag a field from the dataset to a channel

**Comment by arvind** [comment]
Fixed with https://github.com/vega/lyra/commit/ec96a693ee69c756cd3f8e6b1c9b87ac3f28fc71. 

But agreed, the bubble cursor should be more sophisticated. Will create a separate issue for that.
