### ISSUE TITLE
dropping field onto e.g. text value

### ISSUE THREAD

**Issue by jonathanzong** [uwdata/lyra#457]
for text value, this appears to set the value to the name of the field instead of the appropriate values. it would be helpful to have an example of this working so i can adapt it to work for signals as well.

**Comment by arvind** [comment]
Fixed with https://github.com/vega/lyra/commit/fbf2d40b69a6f2beb9a263c7cd361e72dbb3a4f1 and https://github.com/vega/lyra/commit/391e60c6d50d902d2d445146360b61cad6e4e500
