### ISSUE TITLE
this project is so dope

### ISSUE THREAD

**Issue by TaridaGeorge** [uwdata/lyra#473]
OMG. Guys this project is so dope! Thank you for bringing something like this in the opensource field!

A big thank you to all the developers that contributed to this. 

More people should know about this project. 
I came here because at my girlfriend workplace they use vega and I thought that I could use it too for my personal projects.
If it weren't for that I could never find this project. Please consider improving SEO. Improving SEO would make more contributors to show up and more contributors means more features for this awesome project!

#thank-you #a-little-advice

**Comment by jonathanzong** [comment]
Thanks! We plan to do more outreach when we're ready to release Lyra 2.
