### ISSUE TITLE
parseGuides axis deduplication

### ISSUE THREAD

**Issue by jonathanzong** [uwdata/lyra#493]
in findOrCreateAxis under parseGuides, there appears to be logic ensuring that extra axes don't get added when there are already a few defined. But this behavior doesn't appear to work as intended, because redundant axes can be defined (including more than 2 axes on the same orientation).

example: create a symbol and bind a field to x axis. create another symbol (or rect or whatever) and bind the same field to x axis. create a third mark and create a third axis (from the comments in the code, it seems this was intended to be a no-op)

We should spec out the correct/expected behavior for axes. E.g. if you have two axes on the same orientation that visualize the same scale (same field, etc), shouldn't these two definitions just be merged? Or are there cases where you'd want two different axes of the same scale? The scale recycling logic might apply here.

**Comment by jonathanzong** [comment]
https://github.com/vega/lyra/issues/466

**Comment by jonathanzong** [comment]
Bug in parseGuides, related to the title fix in Katie's PR:

steps to repro:
- create symbol
- bind continuous field to y axis
- bind discrete field to x axis
- x axis will not successfully create (def[1] not defined)

**Comment by ktbacher** [comment]
Fixed last comment with PR #510

**Comment by jonathanzong** [comment]
when you add a second field to the same axis, we should union the scales. milestone one can just be replacing the existing field

**Comment by jonathanzong** [comment]
main issue fixed by 1cb1bddceeefd65e45f7e702b17821d015f8d684 and 26d118e2002aba4c2ac20ed6433ad1f4fa06fb94, will file new issue about scale merging
