### ISSUE TITLE
clearer label for legend border color

### ISSUE THREAD

**Issue by jonathanzong** [uwdata/lyra#494]
![Screen Shot 2020-10-05 at 11 33 23 PM](https://user-images.githubusercontent.com/4650077/95156370-6b1b3000-0764-11eb-8eb6-d7a4c3a2a00d.png)

in the inspector, the property control for `gradient > color` actually controls the border color of the legend. Can we give this a clearer label? (Perhaps just `Border` or `Legend Border` instead of `Gradient`)

**Comment by NanaKwame** [comment]
I can take a look at this.

**Comment by NanaKwame** [comment]
Hmm so we already have border color and border width under Legend -> More properties. So I guess we could use the same names here too.
