### ISSUE TITLE
a few unconnected properties in guide inspectors

### ISSUE THREAD

**Issue by jonathanzong** [uwdata/lyra#495]
Axis inspector:

`Title` > `Offset` -- no effect

`Ticks` > `Padding` -- no effect

Legend inspector:

fill:
`Gradient` (border) > `width` -- no default/initial value, but works

size:
`Symbols` > `opacity` --- no effect

`Symbols` > `width` - no initial value, works

**Comment by NanaKwame** [comment]
fill gradient issue is covered in https://github.com/vega/lyra/pull/497/files
sorry didn't see this in time.

**Comment by NanaKwame** [comment]
hmm looks like tick padding isn't really a thing unless I am missing the vega lite equivalent.

also changing title offest to dx offset and dy offset
