### ISSUE TITLE
union scales when binding additional fields

### ISSUE THREAD

**Issue by jonathanzong** [uwdata/lyra#527]
Example:

- create symbol mark
- drop "horsepower" onto "y"
- create another mark
- drop "acceleration" onto "y" for the second mark

this should cause "acceleration" to be unioned with "horsepower" in the existing scale domain

**Comment by arvind** [comment]
Just to make sure we’re on the same page: in the above case, since you’re binding a new field to the same mark, shouldn’t it _override_ the encoding and scale? We should only union scale domain fields when _layering_ marks (ie binding to y on _another_ mark in the _same_ group).

**Comment by jonathanzong** [comment]
thanks for catching that! edited the example above

**Comment by jonathanzong** [comment]
implemented in 41b0d474f62d4868cf52488855200e7c212de117 and 93c9124579bdb9870fc6150d17f86145093df492
