### ISSUE TITLE
Adjusting axis width can break the canvas

### ISSUE THREAD

**Issue by kanitw** [uwdata/lyra#56]
![b0f370f3199ccff905688daab230b8c1](https://f.cloud.github.com/assets/111269/2041541/62fd7e32-89c6-11e3-80f5-36bd1f3a25c7.gif)

Basically I drag axis width to the maximum value and then the canvas becomes crazy large and shows nothing on the screen.  

(No output in the console log though)

**Comment by arvind** [comment]
I suspect this was a Vega bug at the time.
