### ISSUE TITLE
Incomplete specification allowed.

### ISSUE THREAD

**Issue by kanitw** [uwdata/lyra#98]
Current UI allow users to add something and jump to other part before completing the specification 

For example, the user add a pie chart transform. 

![lyra_and_airmail_and_vde__git_](https://f.cloud.github.com/assets/111269/2215743/1d37472c-99fa-11e3-939a-9adf0769d0c5.png)

but leave the angles field empty and jump to something else (e.g., adding another mark).

I think
1) This is prone for bugs.  (Although I currently know the code well enough –you might have ignore all incomplete items.)
2) More importantly,  it’s hard for user to recognize later than actually this mark ("rect alpha”) is not rendered since its specification is incomplete.  

**Check List**
- [ ] #111
- **Scale**
  - [ ] Closing scale popup should automatically remove null items from the value array

- [ ] **Marks**

**Comment by arvind** [comment]
With Lyra 2, we should not export any primitives that do not pass the schema.

**Comment by arvind** [comment]
Going to track via a new issue for simplicity.
